packages:
  esp32-generic-s3: !include esp32-generic-s3.yaml

esphome:
  project:
    name: esphome.bluetooth-proxy
    version: dev

improv_serial:

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/bluetooth-proxy/esp32-generic/manifest.json

http_request:

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-s3.yaml@main
