# Only boards produced after November 1, 2025 are supported
esphome:
  name: seeed-esp32-poe
  friendly_name: Bluetooth Proxy
  min_version: 2025.11.0
  name_add_mac_suffix: true

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

ethernet:
  type: W5500
  clk_pin: GPIO7
  mosi_pin: GPIO9
  miso_pin: GPIO8
  cs_pin: GPIO2
  interrupt_pin: GPIO10

api:
logger:

ota:
  - platform: esphome
    id: ota_esphome

esp32_ble:
  max_connections: 4

esp32_ble_tracker:

bluetooth_proxy:
  active: true
  connection_slots: 4

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
