esphome:
  name: m5stack-atom-s3
  friendly_name: Bluetooth Proxy
  min_version: 2025.2.1
  name_add_mac_suffix: true

esp32:
  board: m5stack-atoms3
  framework:
    type: esp-idf

wifi:
  ap:

api:
logger:

ota:
  - platform: esphome
    id: ota_esphome

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
