esphome:
  name: olimex-esp32-poe-iso
  friendly_name: Bluetooth Proxy
  min_version: 2025.11.0
  name_add_mac_suffix: true

esp32:
  variant: esp32
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0
  power_pin:
    number: GPIO12
    ignore_strapping_warning: true

api:
logger:
ota:
  - platform: esphome
    id: ota_esphome

esp32_ble:
  max_connections: 4

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
  connection_slots: 4

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
