name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - m5stack-atom-lite.yaml
          - esp32-generic.yaml
          - olimex-esp32-poe-iso.yaml
          - wt32-eth01.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.5.2
        with:
          yaml_file: ${{ matrix.file }}
          version: dev
