name: YAML lint

on:
  push:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  yamllint:
    name: 🧹 yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: 🚀 Run yamllint
        run: yamllint --strict .
